// climbing-gallery.js
// Opens/closes the climbing photo albums (the ".hidden-gallery" lightboxes) and
// keeps the interaction keyboard- and screen-reader-accessible. The markup itself
// is generated by build_climbing.py; this only wires up behaviour on the DOM.
(function () {
  "use strict";

  var lastFocused = null; // the album tile to restore focus to after closing

  function closeAll() {
    document.querySelectorAll(".hidden-gallery.open").forEach(function (g) {
      g.classList.remove("open");
      g.setAttribute("aria-hidden", "true");
    });
  }

  function openGallery(id, opener) {
    var gallery = document.getElementById(id);
    if (!gallery) return;
    closeAll();
    lastFocused = opener || document.activeElement;
    gallery.classList.add("open");
    gallery.setAttribute("aria-hidden", "false");
    var closeBtn = gallery.querySelector(".close-btn");
    if (closeBtn) closeBtn.focus();
  }

  function closeGallery(gallery) {
    gallery = gallery || document.querySelector(".hidden-gallery.open");
    if (!gallery) return;
    gallery.classList.remove("open");
    gallery.setAttribute("aria-hidden", "true");
    if (lastFocused && typeof lastFocused.focus === "function") {
      lastFocused.focus();
    }
    lastFocused = null;
  }

  document.addEventListener("DOMContentLoaded", function () {
    // Album cover tiles: click, or Enter/Space when focused via keyboard.
    document.querySelectorAll(".album-item[data-gallery]").forEach(function (tile) {
      var id = tile.getAttribute("data-gallery");
      tile.addEventListener("click", function () {
        openGallery(id, tile);
      });
      tile.addEventListener("keydown", function (e) {
        if (e.key === "Enter" || e.key === " " || e.key === "Spacebar") {
          e.preventDefault(); // stop Space from scrolling the page
          openGallery(id, tile);
        }
      });
    });

    // Each open gallery: close button, plus clicking the dark backdrop closes it.
    document.querySelectorAll(".hidden-gallery").forEach(function (gallery) {
      var closeBtn = gallery.querySelector(".close-btn");
      if (closeBtn) {
        closeBtn.addEventListener("click", function () {
          closeGallery(gallery);
        });
      }
      gallery.addEventListener("click", function (e) {
        if (e.target === gallery) closeGallery(gallery); // backdrop only, not a photo
      });
    });

    // Escape closes whichever gallery is open.
    document.addEventListener("keydown", function (e) {
      if (e.key === "Escape") closeGallery();
    });
  });
})();
