#!/usr/bin/env python3
"""Regenerate the climbing photo gallery in climbing.html from folders on disk.

Each album is a folder under graphics/climbing/. The script scans those folders,
reads a small `album.txt` (and optional per-photo `.txt` sidecars) for titles and
captions, and rewrites the block in climbing.html between the markers:

    <!-- BEGIN GALLERY (auto-generated by build_climbing.py - do not edit by hand) -->
    ...generated...
    <!-- END GALLERY -->

Usage:
    python build_climbing.py

No third-party dependencies (standard library only).

--------------------------------------------------------------------------------
Authoring convention (see graphics/climbing/README.md for the friendly version)
--------------------------------------------------------------------------------
graphics/climbing/<album>/
    album.txt        # optional metadata; `key: value` lines OR just the title text
    cover.jpg        # optional; else a file literally named cover.* / first image
    01_photo.jpg     # any image; sorted by filename (use 01_, 02_ prefixes to order)
    01_photo.txt     # optional sidecar: caption/alt for that photo

Album order AND inclusion are controlled by graphics/climbing/order.txt: one folder
name per line, top line = top of the page. ONLY folders listed there are shown, so
deleting a line hides that album (its files stay on disk). If order.txt is missing,
every folder is shown alphabetically.

album.txt keys (all optional):
    title:   text shown under the cover tile   (default: folder name)
    cover:   filename of the cover image        (default: cover.* file, else 1st image)
    photos:  comma-separated filenames giving an explicit lightbox order; any images
             not listed are appended in filename order. Omit to just use filename
             order (with the cover pulled to the front).

A per-photo sidecar `<photo-basename>.txt`:
    * contains `caption:` / `alt:` lines  -> parsed as those fields, or
    * is plain text                        -> the whole text is the caption (alt = it).
    `alt:` with no `caption:` -> the photo gets alt text but no visible <figcaption>.

Files starting with `OLD` and dotfiles (e.g. .DS_Store) are ignored.
"""

import html
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent
CLIMBING_DIR = REPO_ROOT / "graphics" / "climbing"
HTML_FILE = REPO_ROOT / "climbing.html"

GALLERY_HEADING = "Photo Gallery. Click on an album!"
BEGIN_MARKER = (
    "<!-- BEGIN GALLERY (auto-generated by build_climbing.py - do not edit by hand) -->"
)
END_MARKER = "<!-- END GALLERY -->"

IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".webp", ".gif"}
KNOWN_ALBUM_KEYS = {"title", "cover", "photos"}
ORDER_FILE = CLIMBING_DIR / "order.txt"


def parse_kv(text):
    """Parse `key: value` lines. Returns (dict_of_known_keys, list_of_other_lines)."""
    fields = {}
    other = []
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if ":" in line:
            key, value = line.split(":", 1)
            key = key.strip().lower()
            if key in KNOWN_ALBUM_KEYS or key in ("caption", "alt"):
                fields[key] = value.strip()
                continue
        other.append(line)
    return fields, other


def is_image(path):
    return path.is_file() and path.suffix.lower() in IMAGE_EXTS


def wanted(path):
    """A real, deployable image (not an OLD* backup or a dotfile)."""
    name = path.name
    return is_image(path) and not name.startswith("OLD") and not name.startswith(".")


def album_id(folder_name):
    slug = re.sub(r"[^A-Za-z0-9]+", "-", folder_name).strip("-")
    return "album-" + (slug or "album")


def read_sidecar(folder, image_name):
    """Return (caption, alt) for an image, or (None, None) if no sidecar exists."""
    sidecar = folder / (Path(image_name).stem + ".txt")
    if not sidecar.is_file():
        return None, None
    text = sidecar.read_text(encoding="utf-8").strip()
    fields, other = parse_kv(text)
    if "caption" in fields or "alt" in fields:
        caption = fields.get("caption")
        alt = fields.get("alt", caption)  # alt defaults to the caption
        return caption, alt
    # Plain-text sidecar: the whole file is the caption (and the alt).
    plain = text if text else None
    return plain, plain


def order_photos(images, cover, photos_hint):
    """images: list[str] filenames. Returns them in display order."""
    if photos_hint:
        listed = [f.strip() for f in photos_hint.split(",") if f.strip()]
        ordered = [f for f in listed if f in images]
        rest = sorted((f for f in images if f not in ordered), key=str.lower)
        return ordered + rest
    rest = sorted((f for f in images if f != cover), key=str.lower)
    return ([cover] if cover in images else []) + rest


def load_album(folder):
    images = sorted((p.name for p in folder.iterdir() if wanted(p)), key=str.lower)
    if not images:
        return None

    meta = {}
    other_lines = []
    album_txt = folder / "album.txt"
    if album_txt.is_file():
        meta, other_lines = parse_kv(album_txt.read_text(encoding="utf-8"))

    title = meta.get("title")
    if not title and other_lines:  # bare-text album.txt -> first line is the title
        title = other_lines[0]
    if not title:
        title = folder.name

    cover = meta.get("cover")
    if cover not in images:
        cover_named = next((f for f in images if Path(f).stem.lower() == "cover"), None)
        cover = cover_named or images[0]

    ordered = order_photos(images, cover, meta.get("photos"))
    photos = []
    for name in ordered:
        caption, alt = read_sidecar(folder, name)
        if not alt:
            alt = title  # never leave alt empty (accessibility)
        photos.append({"name": name, "caption": caption, "alt": alt})

    return {
        "id": album_id(folder.name),
        "folder": folder.name,
        "title": title,
        "cover": cover,
        "photos": photos,
        "has_album_txt": album_txt.is_file(),
    }


def read_order():
    """Return folder names listed in order.txt (top-to-bottom), or None if absent."""
    if not ORDER_FILE.is_file():
        return None
    names = []
    for raw in ORDER_FILE.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if line and not line.startswith("#"):
            names.append(line)
    return names


def find_albums():
    order = read_order()
    if order is None:
        print(
            "WARNING: graphics/climbing/order.txt not found - showing every album "
            "folder alphabetically. Create order.txt to control order and inclusion."
        )
        folders = [
            f
            for f in sorted(CLIMBING_DIR.iterdir(), key=lambda p: p.name.lower())
            if f.is_dir() and not f.name.startswith(".")
        ]
    else:
        # order.txt is authoritative: only listed folders appear, in listed order.
        folders = []
        for name in order:
            folder = CLIMBING_DIR / name
            if folder.is_dir():
                folders.append(folder)
            else:
                print(f"WARNING: order.txt lists '{name}' but that folder does not exist - skipping.")

    albums = []
    for folder in folders:
        album = load_album(folder)
        if album:
            albums.append(album)
        else:
            print(f"WARNING: '{folder.name}' has no images - skipping.")

    # Ensure unique ids even if two folder names slugify identically.
    seen = {}
    for album in albums:
        base = album["id"]
        n = seen.get(base, 0)
        if n:
            album["id"] = f"{base}-{n + 1}"
        seen[base] = n + 1
    return albums


def esc(text):
    return html.escape(text or "", quote=True)


def src_for(album, image_name):
    return f"graphics/climbing/{album['folder']}/{image_name}"


def render(albums):
    tiles = []
    for a in albums:
        tiles.append(
            f'        <figure class="album-item" role="button" tabindex="0"\n'
            f'                data-gallery="{esc(a["id"])}" aria-label="Open album: {esc(a["title"])}">\n'
            f'          <img loading="lazy" src="{esc(src_for(a, a["cover"]))}" alt="">\n'
            f"          <figcaption>{esc(a['title'])}</figcaption>\n"
            f"        </figure>"
        )

    galleries = []
    for a in albums:
        figures = []
        for p in a["photos"]:
            caption_html = (
                f"\n        <figcaption>{esc(p['caption'])}</figcaption>"
                if p["caption"]
                else ""
            )
            figures.append(
                f"      <figure>\n"
                f'        <img loading="lazy" src="{esc(src_for(a, p["name"]))}" alt="{esc(p["alt"])}">'
                f"{caption_html}\n"
                f"      </figure>"
            )
        galleries.append(
            f'    <div class="hidden-gallery" id="{esc(a["id"])}" role="dialog" aria-modal="true"\n'
            f'         aria-label="{esc(a["title"])}" aria-hidden="true">\n'
            f'      <button type="button" class="close-btn" aria-label="Close gallery">&times;</button>\n'
            + "\n".join(figures)
            + "\n    </div>"
        )

    return (
        '    <div class="gallery-container">\n'
        f'      <h2 style="font-size: 22px; padding-bottom: 20px;">{esc(GALLERY_HEADING)}</h2>\n'
        '      <div class="album-grid">\n'
        + "\n\n".join(tiles)
        + "\n      </div>\n"
        "    </div>\n"
        "    <!-- Hidden Galleries for Each Album -->\n"
        + "\n\n".join(galleries)
    )


def splice_into_html(generated):
    source = HTML_FILE.read_text(encoding="utf-8")
    if BEGIN_MARKER not in source or END_MARKER not in source:
        sys.exit(
            f"ERROR: could not find the gallery markers in {HTML_FILE.name}.\n"
            f"Add these two lines around the gallery region first:\n"
            f"    {BEGIN_MARKER}\n    {END_MARKER}"
        )
    block = f"{BEGIN_MARKER}\n{generated}\n    {END_MARKER}"
    pattern = re.compile(re.escape(BEGIN_MARKER) + r".*?" + re.escape(END_MARKER), re.DOTALL)
    updated = pattern.sub(lambda _: block, source, count=1)
    if updated != source:
        HTML_FILE.write_text(updated, encoding="utf-8")
    return updated != source


def main():
    if not CLIMBING_DIR.is_dir():
        sys.exit(f"ERROR: {CLIMBING_DIR} does not exist.")

    albums = find_albums()
    if not albums:
        sys.exit(f"ERROR: no album folders with images found in {CLIMBING_DIR}.")

    generated = render(albums)
    changed = splice_into_html(generated)

    print(f"Generated gallery from {len(albums)} album(s):")
    for a in albums:
        warn = "" if a["has_album_txt"] else "  (no album.txt - using folder name as title)"
        missing_alt = sum(1 for p in a["photos"] if p["alt"] == a["title"])
        alt_note = f"  [{missing_alt} photo(s) using fallback alt]" if missing_alt else ""
        print(
            f"  - {a['folder']}: {len(a['photos'])} photo(s), cover={a['cover']}{warn}{alt_note}"
        )
    print(f"\n{HTML_FILE.name}: {'updated' if changed else 'already up to date'}.")


if __name__ == "__main__":
    main()
